VGG16:
  include_top: false
  weights: imagenet
  input_tensor: null
  input_shape: null
  pooling: null
  classes: 2  # Number of classes for binary classification
  classifier_activation: sigmoid  # Use sigmoid activation for binary classification
  name: vgg16

AUGMENTATION: true
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
EPOCHS: 1
LEARNING_RATE: 0.01
